version: 2
updates:
  - package-ecosystem: "npm" # Backend
    directory: "/backend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "npm" # Frontend
    directory: "/Frontend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "cargo" # Smart Contracts
    directory: "/contracts/cinderx"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "github-actions" # GitHub Actions
    directory: "/"
    schedule:
      interval: "weekly"
